name: Taming the BEAST
description: BEAST2 tutorials for the community, by the community!
url: https://taming-the-beast.org/

permalink: /:categories/:title/
future: true

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.log,gz"
  - "*.nb"
  - "*.trees"
  - "*.trees.gz"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
  - "github.token"

defaults:
  -
    scope:
      path: "contribute/Hosting-guide"
    values:
      layout: "post"
  -
    scope:
      path: "contribute/Hosting-guide-printable"
    values:
      layout: "post-printable"

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: /tutorials
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


tutorials:
  - taming-the-beast/Introduction-to-BEAST2
  - taming-the-beast/Troubleshooting-convergence-issues
  - taming-the-beast/Troubleshooting-initialization-issues
  - nicfel/AIM-Tutorial
  - taming-the-beast/Bacter-Tutorial
  - nicfel/CoupledMCMC-Tutorial
  - rachelwarnock/BDMM-Prime-for-macroevolution
  - genomescale/calibrated-species-trees
  - mmatschiner/CladeAge-Tutorial
  - bjoelle/ClaDS-tutorial
  - taming-the-beast/FBD-tutorial
  - nicfel/Reassortment-Tutorial
  - KonstantinHoffmann/LanguagePhylogenies
  - taming-the-beast/Molecular-Dating-Tutorial
  - taming-the-BEAST/Mascot-Tutorial
  - duchene/adequacy_tutorial
  #- rbouckaert/NS-tutorial
  - sgtRoberty/NS-tutorial
  - taming-the-beast/Molecular-clock-dating-and-modelling-rate-variation
  - bjoelle/MSBD-tutorial
  - boskovav/PIQMEE-Tutorial
  - taming-the-beast/Prior-selection
  - taming-the-beast/SCOTTI-Tutorial
  - bethany-j-allen/Skyline-analyses-for-macroevolution
  - taming-the-beast/Skyline-plots
  - bjoelle/BFD_snapper_tutorial
  - genomescale/starbeast2-tutorial
  - taming-the-beast/StarBeast3-Tutorial
  - taming-the-beast/Structured-coalescent
  - taming-the-beast/Structured-birth-death-model
  - taming-the-beast/Substitution-model-averaging
  - walterxie/MEP-tutorial
  - bethany-j-allen/Total-Evidence-Tutorial
  - taming-the-beast/Visualizing-BEAST2-results

 # Deprecated
 #- genomescale/species-tree-clocks
 #- taming-the-beast/StarBeast-Tutorial

plugins:
  - jekyll-katex
  - jekyll-scholar
