name: Taming the BEAST
description: BEAST2 tutorials for the community, by the community!
url: https://taming-the-beast.org/

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet: 
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  group_by: none
  group_order: ascending

  source: /tutorials
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"


tutorials:
  - taming-the-beast/Introduction-to-BEAST2
  - taming-the-beast/Prior-selection
  - taming-the-beast/Troubleshooting
  - taming-the-beast/Skyline-plots
  - taming-the-beast/Substitution-model-averaging
  - taming-the-beast/FBD-tutorial
  - taming-the-beast/Bacter-Tutorial
  - taming-the-beast/StarBeast-Tutorial
  - taming-the-beast/Molecular-Dating-Tutorial
  - genomescale/species-tree-clocks
  - genomescale/calibrated-species-trees
  - taming-the-beast/Structured-coalescent
  - taming-the-beast/Structured-birth-death-model
  - nicfel/Mascot-Tutorial
  - taming-the-beast/SCOTTI-Tutorial
  - duchene/adequacy_tutorial
  - genomescale/starbeast2-tutorial
  - mmatschiner/CladeAge-Tutorial
