name: Create and push docker image for TTB website building environment

on:
  push:
    branches: [ "master" ]
    paths: ["Dockerfile"]
  pull_request:
    branches: [ "master" ]
    paths: ["Dockerfile"]
  workflow_dispatch:

jobs:

  build_and_publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true 
        tags: ghcr.io/taming-the-beast/ttb-web-build-env:latest
    - name: Verify the image was pushed
      run: docker pull ghcr.io/taming-the-beast/ttb-web-build-env:latest
